# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('value', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sonnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1400)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='sonnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonnit_server.Sonnet'),
        ),
    ]
