# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonnit_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.IntegerField(),
        ),
    ]
